config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: 'homes#top'
get 'books' => 'books#index'
post 'books' => 'books#create'
get 'books/:id' => 'books#show', as: 'book'
get 'books/:id/edit' => 'books#edit', as: 'edit_book'
patch 'books/:id' => 'books#update', as: 'update_book'
delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   validates :title, presence: true
   validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
   @book = Book.new(book_params)
   if  @book.save
  # 詳細ページへリダイレクト
   redirect_to book_path(@book), notice: 'Book was successfully created.'
   else
    @books = Book.all
    render 'index'
   end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
   @book = Book.find(params[:id])
   if @book.update(book_params)
    redirect_to book_path(@book), notice: 'Book was successfully updated.'
   else
     render 'edit'
   end

  end


  def destroy
    book = Book.find(params[:id])
    if book.destroy
    # 一覧ページへリダイレクト
    redirect_to books_path, notice: 'Book was successfully destroyed.'
    end
  end



  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model:@book, local: true do |f| %>

 <!--バリデーションエラーメッセージ-->
  <% if @book.errors.any? %>
  <div class="alert">
    <h2 class=alert_title><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
        <% end %>
     </ul>

  </div>
 <% end %>

 <div class="form">
<label for="book_title">Title</label></br>
<%= f.text_field :title %></br>
</div>

<div class="form">
  <label for="book_body">Body</label></br>
<%= f.text_area :body %></br>
</div>

<div class="action">
<%= f.submit'Update Book' %>
</div>
<% end %>


<div class="link">
  <%= link_to "Show", book_path(@book) %>
  |
  <%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb
<!--destroyのフラッシュメッセージ-->
<div class="flash">
<%= flash[:notice] %>
</div>
<!--一覧ページ-->
<h1>Books</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
  </tr>
  <!--ここから繰り返しの処理-->
  <% @books.each do |book| %>
  <tr>
    <!--投稿データの読み込み-->
    <td>
      <%= book.title %>
    </td>
    <td>
      <%= book.body %>
    </td>
    <td>
     <!--show,edit,destroyのリンク-->
     <%= link_to "Show", book_path(book.id) %>
     <%= link_to "Edit", edit_book_path(book.id) %>
     <%= link_to "Destroy", destroy_book_path(book.id), method: :delete, data: { confirm: "Are you sure?"} %>
    </td>
  </tr>
  <% end %>
</table>

<!--投稿フォーム-->
 <h2>New book</h2>

<%= form_with model:@book, local:true do |f| %>

<!--バリデーションエラーメッセージ-->
  <% if @book.errors.any? %>
    <div class="alert">
    <h2 class="alert_title"><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
       </ul>
    </div>
     <% end %>

     <div class="form">
     <label for="book_title">Title</label></br>
     <%= f.text_field :title %>
     </div>
    <div class="form">
     <label for="book_body">Body</label></br>
     <%= f.text_area :body %>
    </div>
    <div class="form">
     <%= f.submit 'Create Book' %>
    </div>

<% end %>

app/views/books/show.html.erb
<!--createのフラッシュメッセージ-->
<p class=flash>
<%= flash[:notice] %>
</p>


  <p>
    <strong>Title:</strong><%= @book.title %>
  </p>

  <p>
    <strong>Body:</strong><%= @book.body %>
  </p>

  <!--編集・一覧ページへのリンク-->
  <div class="link">
  <%= link_to "Edit", edit_book_path(@book) %>
  |
  <%= link_to "Back", books_path %>
  </div>

app/views/homes/top.html.erb
<h1>ようこそ<strong>Bookers </strong>へ！</h1>

<div class="text">
  <p><storong>Bookers</storong>では、さまざまな書籍に関するあなたの意見や</p>
  <p>印象を共有し交換することができます</p>
 </div>

 <p>
   <!--一覧ページへのリンク-->
   <%= link_to "Start", books_path %>
 </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>